ord_api_url: "https://charlie.ordinals.net"
electrs_api_url: "https://btc-1.xverse.app"
mempool_space_api_url: "https://memproxy.inscribe.dev/api"
theme: "spam-classic"
page_size: 24
artist_name: "Bitcoin Knotzis"
artist_avatar_url: "https://pbs.twimg.com/profile_images/2016120143307276288/HDUqbTAA_400x400.jpg"
artist_about: "The End of Ordinals is upon us, BIP110 and CAT-nip administered by the Knotzi regime is begining to plague the blockchain. All mining has stopped! All Transactions are filtered! There is only 1 route to salvation, we must adorne the Knotzi culture, a disguise, our trojan horse, so that we can destroy their regime, from the inside out! Join us today and help keep SPAM on its merry way!"
social_x_url: "https://x.com/A_Knotler"
social_website_url: ""
social_github_url: ""
brand_logo_url: "/bitcoin-knotzis-logo.png"
header_loop_gif_url: "/bitcoin-knotzis-header-loop.gif"
launchpad_media_gif_url: "/bitcoin-knotzis-mint-loop.gif"
home_box_title: "About us"